// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openiot/sensor/multisensor.proto

package sensor

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MultiSensorStatus struct {
	Temperature  *Temperature  `protobuf:"bytes,1,opt,name=temperature,proto3" json:"temperature,omitempty"`
	Humidity     *Humidity     `protobuf:"bytes,2,opt,name=humidity,proto3" json:"humidity,omitempty"`
	AmbientLight *AmbientLight `protobuf:"bytes,3,opt,name=ambient_light,json=ambientLight,proto3" json:"ambient_light,omitempty"`
	// For battery power sensors - current battery state
	Battery *Battery `protobuf:"bytes,10,opt,name=battery,proto3" json:"battery,omitempty"`
	// Optional device uptime, in ms
	Uptime               uint32   `protobuf:"varint,11,opt,name=uptime,proto3" json:"uptime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MultiSensorStatus) Reset()         { *m = MultiSensorStatus{} }
func (m *MultiSensorStatus) String() string { return proto.CompactTextString(m) }
func (*MultiSensorStatus) ProtoMessage()    {}
func (*MultiSensorStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b0e3be80a44983f, []int{0}
}

func (m *MultiSensorStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MultiSensorStatus.Unmarshal(m, b)
}
func (m *MultiSensorStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MultiSensorStatus.Marshal(b, m, deterministic)
}
func (m *MultiSensorStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MultiSensorStatus.Merge(m, src)
}
func (m *MultiSensorStatus) XXX_Size() int {
	return xxx_messageInfo_MultiSensorStatus.Size(m)
}
func (m *MultiSensorStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_MultiSensorStatus.DiscardUnknown(m)
}

var xxx_messageInfo_MultiSensorStatus proto.InternalMessageInfo

func (m *MultiSensorStatus) GetTemperature() *Temperature {
	if m != nil {
		return m.Temperature
	}
	return nil
}

func (m *MultiSensorStatus) GetHumidity() *Humidity {
	if m != nil {
		return m.Humidity
	}
	return nil
}

func (m *MultiSensorStatus) GetAmbientLight() *AmbientLight {
	if m != nil {
		return m.AmbientLight
	}
	return nil
}

func (m *MultiSensorStatus) GetBattery() *Battery {
	if m != nil {
		return m.Battery
	}
	return nil
}

func (m *MultiSensorStatus) GetUptime() uint32 {
	if m != nil {
		return m.Uptime
	}
	return 0
}

type Temperature struct {
	ValueC               float32  `protobuf:"fixed32,1,opt,name=value_c,json=valueC,proto3" json:"value_c,omitempty"`
	ValueF               float32  `protobuf:"fixed32,2,opt,name=value_f,json=valueF,proto3" json:"value_f,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Temperature) Reset()         { *m = Temperature{} }
func (m *Temperature) String() string { return proto.CompactTextString(m) }
func (*Temperature) ProtoMessage()    {}
func (*Temperature) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b0e3be80a44983f, []int{1}
}

func (m *Temperature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Temperature.Unmarshal(m, b)
}
func (m *Temperature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Temperature.Marshal(b, m, deterministic)
}
func (m *Temperature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Temperature.Merge(m, src)
}
func (m *Temperature) XXX_Size() int {
	return xxx_messageInfo_Temperature.Size(m)
}
func (m *Temperature) XXX_DiscardUnknown() {
	xxx_messageInfo_Temperature.DiscardUnknown(m)
}

var xxx_messageInfo_Temperature proto.InternalMessageInfo

func (m *Temperature) GetValueC() float32 {
	if m != nil {
		return m.ValueC
	}
	return 0
}

func (m *Temperature) GetValueF() float32 {
	if m != nil {
		return m.ValueF
	}
	return 0
}

type Humidity struct {
	RelativePercent      uint32   `protobuf:"varint,1,opt,name=relative_percent,json=relativePercent,proto3" json:"relative_percent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Humidity) Reset()         { *m = Humidity{} }
func (m *Humidity) String() string { return proto.CompactTextString(m) }
func (*Humidity) ProtoMessage()    {}
func (*Humidity) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b0e3be80a44983f, []int{2}
}

func (m *Humidity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Humidity.Unmarshal(m, b)
}
func (m *Humidity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Humidity.Marshal(b, m, deterministic)
}
func (m *Humidity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Humidity.Merge(m, src)
}
func (m *Humidity) XXX_Size() int {
	return xxx_messageInfo_Humidity.Size(m)
}
func (m *Humidity) XXX_DiscardUnknown() {
	xxx_messageInfo_Humidity.DiscardUnknown(m)
}

var xxx_messageInfo_Humidity proto.InternalMessageInfo

func (m *Humidity) GetRelativePercent() uint32 {
	if m != nil {
		return m.RelativePercent
	}
	return 0
}

type Battery struct {
	Percent              uint32   `protobuf:"varint,1,opt,name=percent,proto3" json:"percent,omitempty"`
	VoltageMv            uint32   `protobuf:"varint,2,opt,name=voltage_mv,json=voltageMv,proto3" json:"voltage_mv,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Battery) Reset()         { *m = Battery{} }
func (m *Battery) String() string { return proto.CompactTextString(m) }
func (*Battery) ProtoMessage()    {}
func (*Battery) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b0e3be80a44983f, []int{3}
}

func (m *Battery) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Battery.Unmarshal(m, b)
}
func (m *Battery) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Battery.Marshal(b, m, deterministic)
}
func (m *Battery) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Battery.Merge(m, src)
}
func (m *Battery) XXX_Size() int {
	return xxx_messageInfo_Battery.Size(m)
}
func (m *Battery) XXX_DiscardUnknown() {
	xxx_messageInfo_Battery.DiscardUnknown(m)
}

var xxx_messageInfo_Battery proto.InternalMessageInfo

func (m *Battery) GetPercent() uint32 {
	if m != nil {
		return m.Percent
	}
	return 0
}

func (m *Battery) GetVoltageMv() uint32 {
	if m != nil {
		return m.VoltageMv
	}
	return 0
}

type AmbientLight struct {
	Value                uint32   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AmbientLight) Reset()         { *m = AmbientLight{} }
func (m *AmbientLight) String() string { return proto.CompactTextString(m) }
func (*AmbientLight) ProtoMessage()    {}
func (*AmbientLight) Descriptor() ([]byte, []int) {
	return fileDescriptor_7b0e3be80a44983f, []int{4}
}

func (m *AmbientLight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AmbientLight.Unmarshal(m, b)
}
func (m *AmbientLight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AmbientLight.Marshal(b, m, deterministic)
}
func (m *AmbientLight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AmbientLight.Merge(m, src)
}
func (m *AmbientLight) XXX_Size() int {
	return xxx_messageInfo_AmbientLight.Size(m)
}
func (m *AmbientLight) XXX_DiscardUnknown() {
	xxx_messageInfo_AmbientLight.DiscardUnknown(m)
}

var xxx_messageInfo_AmbientLight proto.InternalMessageInfo

func (m *AmbientLight) GetValue() uint32 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*MultiSensorStatus)(nil), "sensor.MultiSensorStatus")
	proto.RegisterType((*Temperature)(nil), "sensor.Temperature")
	proto.RegisterType((*Humidity)(nil), "sensor.Humidity")
	proto.RegisterType((*Battery)(nil), "sensor.Battery")
	proto.RegisterType((*AmbientLight)(nil), "sensor.AmbientLight")
}

func init() {
	proto.RegisterFile("openiot/sensor/multisensor.proto", fileDescriptor_7b0e3be80a44983f)
}

var fileDescriptor_7b0e3be80a44983f = []byte{
	// 315 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0xcf, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0xbf, 0x7c, 0x93, 0x3a, 0x69, 0x68, 0x5d, 0x8b, 0xe6, 0x22, 0x94, 0xe0, 0xa1,
	0x05, 0x69, 0x41, 0xe9, 0xc1, 0x93, 0x58, 0x41, 0x3c, 0x58, 0x90, 0xad, 0xf7, 0xb0, 0xad, 0x63,
	0xbb, 0x90, 0x5f, 0x6c, 0x27, 0x81, 0xfe, 0xe3, 0x9e, 0xa5, 0xfb, 0xc3, 0xc6, 0x5b, 0xde, 0xfb,
	0xcc, 0x9b, 0xcc, 0x4b, 0x60, 0x54, 0x56, 0x58, 0xc8, 0x92, 0x66, 0x7b, 0x2c, 0xf6, 0xa5, 0x9a,
	0xe5, 0x75, 0x46, 0xd2, 0x3c, 0x4f, 0x2b, 0x55, 0x52, 0xc9, 0x7c, 0xa3, 0x92, 0x6f, 0x0f, 0xce,
	0x97, 0x47, 0xba, 0xd2, 0x7a, 0x45, 0x82, 0xea, 0x3d, 0x9b, 0x43, 0x48, 0x98, 0x57, 0xa8, 0x04,
	0xd5, 0x0a, 0x63, 0x6f, 0xe4, 0x8d, 0xc3, 0xbb, 0x8b, 0xa9, 0xdd, 0xf0, 0x71, 0x42, 0xbc, 0x3d,
	0xc7, 0x6e, 0xa1, 0xbb, 0xab, 0x73, 0xf9, 0x29, 0xe9, 0x10, 0x77, 0x74, 0x66, 0xe0, 0x32, 0xaf,
	0xd6, 0xe7, 0xbf, 0x13, 0xec, 0x01, 0x22, 0x91, 0xaf, 0x25, 0x16, 0x94, 0x66, 0x72, 0xbb, 0xa3,
	0xf8, 0x9f, 0x8e, 0x0c, 0x5d, 0xe4, 0xc9, 0xc0, 0xb7, 0x23, 0xe3, 0x3d, 0xd1, 0x52, 0x6c, 0x02,
	0xc1, 0x5a, 0x10, 0xa1, 0x3a, 0xc4, 0xa0, 0x43, 0x7d, 0x17, 0x5a, 0x18, 0x9b, 0x3b, 0xce, 0x2e,
	0xc1, 0xaf, 0x2b, 0x92, 0x39, 0xc6, 0xe1, 0xc8, 0x1b, 0x47, 0xdc, 0xaa, 0xe4, 0x11, 0xc2, 0x56,
	0x0f, 0x76, 0x05, 0x41, 0x23, 0xb2, 0x1a, 0xd3, 0x8d, 0x6e, 0xdb, 0xe1, 0xbe, 0x96, 0xcf, 0x27,
	0xf0, 0xa5, 0x2b, 0x39, 0xf0, 0x92, 0xcc, 0xa1, 0xeb, 0x4a, 0xb1, 0x09, 0x0c, 0x14, 0x66, 0x82,
	0x64, 0x83, 0x69, 0x85, 0x6a, 0x83, 0x05, 0xe9, 0x35, 0x11, 0xef, 0x3b, 0xff, 0xdd, 0xd8, 0xc9,
	0x02, 0x02, 0x7b, 0x23, 0x8b, 0x21, 0xf8, 0x3b, 0xec, 0x24, 0xbb, 0x06, 0x68, 0xca, 0x8c, 0xc4,
	0x16, 0xd3, 0xbc, 0xd1, 0xef, 0x8d, 0xf8, 0x99, 0x75, 0x96, 0x4d, 0x72, 0x03, 0xbd, 0xf6, 0xc7,
	0x61, 0x43, 0xf8, 0xaf, 0x8f, 0xb2, 0x6b, 0x8c, 0x58, 0xfb, 0xfa, 0x4f, 0xdf, 0xff, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x97, 0xed, 0xfd, 0xd1, 0x0d, 0x02, 0x00, 0x00,
}
