/* Automatically generated nanopb header */
/* Generated by 0.4.1-dev */

#ifndef PB_OPENIOT_OPENIOT_SYSTEM_PB_H_INCLUDED
#define PB_OPENIOT_OPENIOT_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _EncryptionType {
    EncryptionType_PLAIN = 0,
    EncryptionType_AES_ECB = 1,
    EncryptionType_AES_CBC = 2
} EncryptionType;

/* Struct definitions */
typedef struct _JoinRequest {
    pb_callback_t name;
    pb_callback_t manufacturer;
    pb_callback_t product_url;
    pb_callback_t protobuf_url;
    pb_callback_t default_handler;
} JoinRequest;

typedef struct _LeaveRequest {
    pb_callback_t reason;
} LeaveRequest;

typedef struct _LeaveResponse {
    char dummy_field;
} LeaveResponse;

typedef struct _Header {
    uint64_t device_id;
    uint32_t crc;
    bool key_exchange;
    bool join_request;
    pb_byte_t aes_iv[16];
} Header;

typedef struct _JoinResponse {
    pb_callback_t name;
    int64_t timestamp;
} JoinResponse;

typedef struct _KeyExchangeRequest {
    uint64_t dh_p;
    uint64_t dh_g;
    pb_size_t dh_a_count;
    uint32_t dh_a[16];
    EncryptionType encryption_type;
} KeyExchangeRequest;

typedef struct _KeyExchangeResponse {
    pb_size_t dh_b_count;
    uint32_t dh_b[16];
} KeyExchangeResponse;

typedef struct _MessageInfo {
    uint32_t sequence;
    pb_callback_t proto_name;
} MessageInfo;


/* Helper constants for enums */
#define _EncryptionType_MIN EncryptionType_PLAIN
#define _EncryptionType_MAX EncryptionType_AES_CBC
#define _EncryptionType_ARRAYSIZE ((EncryptionType)(EncryptionType_AES_CBC+1))


/* Initializer values for message structs */
#define Header_init_default                      {0, 0, 0, 0, {0}}
#define MessageInfo_init_default                 {0, {{NULL}, NULL}}
#define KeyExchangeRequest_init_default          {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, _EncryptionType_MIN}
#define KeyExchangeResponse_init_default         {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define JoinRequest_init_default                 {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define JoinResponse_init_default                {{{NULL}, NULL}, 0}
#define LeaveRequest_init_default                {{{NULL}, NULL}}
#define LeaveResponse_init_default               {0}
#define Header_init_zero                         {0, 0, 0, 0, {0}}
#define MessageInfo_init_zero                    {0, {{NULL}, NULL}}
#define KeyExchangeRequest_init_zero             {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, _EncryptionType_MIN}
#define KeyExchangeResponse_init_zero            {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define JoinRequest_init_zero                    {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define JoinResponse_init_zero                   {{{NULL}, NULL}, 0}
#define LeaveRequest_init_zero                   {{{NULL}, NULL}}
#define LeaveResponse_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define JoinRequest_name_tag                     1
#define JoinRequest_manufacturer_tag             2
#define JoinRequest_product_url_tag              3
#define JoinRequest_protobuf_url_tag             4
#define JoinRequest_default_handler_tag          5
#define LeaveRequest_reason_tag                  1
#define Header_device_id_tag                     100
#define Header_crc_tag                           101
#define Header_key_exchange_tag                  102
#define Header_join_request_tag                  103
#define Header_aes_iv_tag                        104
#define JoinResponse_name_tag                    1
#define JoinResponse_timestamp_tag               2
#define KeyExchangeRequest_dh_p_tag              1
#define KeyExchangeRequest_dh_g_tag              2
#define KeyExchangeRequest_dh_a_tag              3
#define KeyExchangeRequest_encryption_type_tag   4
#define KeyExchangeResponse_dh_b_tag             1
#define MessageInfo_sequence_tag                 1
#define MessageInfo_proto_name_tag               2

/* Struct field encoding specification for nanopb */
#define Header_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   device_id,       100) \
X(a, STATIC,   SINGULAR, UINT32,   crc,             101) \
X(a, STATIC,   SINGULAR, BOOL,     key_exchange,    102) \
X(a, STATIC,   SINGULAR, BOOL,     join_request,    103) \
X(a, STATIC,   SINGULAR, FIXED_LENGTH_BYTES, aes_iv,          104)
#define Header_CALLBACK NULL
#define Header_DEFAULT NULL

#define MessageInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sequence,          1) \
X(a, CALLBACK, SINGULAR, STRING,   proto_name,        2)
#define MessageInfo_CALLBACK pb_default_field_callback
#define MessageInfo_DEFAULT NULL

#define KeyExchangeRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   dh_p,              1) \
X(a, STATIC,   SINGULAR, UINT64,   dh_g,              2) \
X(a, STATIC,   REPEATED, UINT32,   dh_a,              3) \
X(a, STATIC,   SINGULAR, UENUM,    encryption_type,   4)
#define KeyExchangeRequest_CALLBACK NULL
#define KeyExchangeRequest_DEFAULT NULL

#define KeyExchangeResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   dh_b,              1)
#define KeyExchangeResponse_CALLBACK NULL
#define KeyExchangeResponse_DEFAULT NULL

#define JoinRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   manufacturer,      2) \
X(a, CALLBACK, SINGULAR, STRING,   product_url,       3) \
X(a, CALLBACK, SINGULAR, STRING,   protobuf_url,      4) \
X(a, CALLBACK, SINGULAR, STRING,   default_handler,   5)
#define JoinRequest_CALLBACK pb_default_field_callback
#define JoinRequest_DEFAULT NULL

#define JoinResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, STATIC,   SINGULAR, INT64,    timestamp,         2)
#define JoinResponse_CALLBACK pb_default_field_callback
#define JoinResponse_DEFAULT NULL

#define LeaveRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            1)
#define LeaveRequest_CALLBACK pb_default_field_callback
#define LeaveRequest_DEFAULT NULL

#define LeaveResponse_FIELDLIST(X, a) \

#define LeaveResponse_CALLBACK NULL
#define LeaveResponse_DEFAULT NULL

extern const pb_msgdesc_t Header_msg;
extern const pb_msgdesc_t MessageInfo_msg;
extern const pb_msgdesc_t KeyExchangeRequest_msg;
extern const pb_msgdesc_t KeyExchangeResponse_msg;
extern const pb_msgdesc_t JoinRequest_msg;
extern const pb_msgdesc_t JoinResponse_msg;
extern const pb_msgdesc_t LeaveRequest_msg;
extern const pb_msgdesc_t LeaveResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Header_fields &Header_msg
#define MessageInfo_fields &MessageInfo_msg
#define KeyExchangeRequest_fields &KeyExchangeRequest_msg
#define KeyExchangeResponse_fields &KeyExchangeResponse_msg
#define JoinRequest_fields &JoinRequest_msg
#define JoinResponse_fields &JoinResponse_msg
#define LeaveRequest_fields &LeaveRequest_msg
#define LeaveResponse_fields &LeaveResponse_msg

/* Maximum encoded size of messages (where known) */
#define Header_size                              44
/* MessageInfo_size depends on runtime parameters */
#define KeyExchangeRequest_size                  120
#define KeyExchangeResponse_size                 96
/* JoinRequest_size depends on runtime parameters */
/* JoinResponse_size depends on runtime parameters */
/* LeaveRequest_size depends on runtime parameters */
#define LeaveResponse_size                       0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
