/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "openiot/system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, 2)


PB_BIND(MessageInfo, MessageInfo, AUTO)


PB_BIND(KeyExchangeRequest, KeyExchangeRequest, AUTO)


PB_BIND(KeyExchangeResponse, KeyExchangeResponse, AUTO)


PB_BIND(JoinRequest, JoinRequest, AUTO)


PB_BIND(JoinResponse, JoinResponse, AUTO)


PB_BIND(LeaveRequest, LeaveRequest, AUTO)


PB_BIND(LeaveResponse, LeaveResponse, AUTO)




