// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common.proto

package openiot

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	any "github.com/golang/protobuf/ptypes/any"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Header struct {
	// Unique (at least at given local network) device ID. It must always
	// be un-encrypted to let device/controller find decryption key.
	// Should also match Message.device_id
	DeviceId uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Encryption parameters
	//
	// Types that are valid to be assigned to Encryption:
	//	*Header_Plain
	//	*Header_AesIv
	Encryption           isHeader_Encryption `protobuf_oneof:"encryption"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

type isHeader_Encryption interface {
	isHeader_Encryption()
}

type Header_Plain struct {
	Plain bool `protobuf:"varint,5,opt,name=plain,proto3,oneof"`
}

type Header_AesIv struct {
	AesIv []byte `protobuf:"bytes,6,opt,name=aes_iv,json=aesIv,proto3,oneof"`
}

func (*Header_Plain) isHeader_Encryption() {}

func (*Header_AesIv) isHeader_Encryption() {}

func (m *Header) GetEncryption() isHeader_Encryption {
	if m != nil {
		return m.Encryption
	}
	return nil
}

func (m *Header) GetPlain() bool {
	if x, ok := m.GetEncryption().(*Header_Plain); ok {
		return x.Plain
	}
	return false
}

func (m *Header) GetAesIv() []byte {
	if x, ok := m.GetEncryption().(*Header_AesIv); ok {
		return x.AesIv
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Header) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Header_Plain)(nil),
		(*Header_AesIv)(nil),
	}
}

type Message struct {
	// The same device id as in EcryptionHeader.
	// Serves mostly to validate successful decryption
	DeviceId uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Auto-incremented sequence number to drop duplicates
	// Even if device / controller will be sending
	// updates every second - counter will last in about 136 years
	Sequence uint32 `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Actual message
	Message              *any.Any `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_555bd8c177793206, []int{1}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Message) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

func (m *Message) GetMessage() *any.Any {
	if m != nil {
		return m.Message
	}
	return nil
}

func init() {
	proto.RegisterType((*Header)(nil), "openiot.Header")
	proto.RegisterType((*Message)(nil), "openiot.Message")
}

func init() { proto.RegisterFile("common.proto", fileDescriptor_555bd8c177793206) }

var fileDescriptor_555bd8c177793206 = []byte{
	// 217 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x8f, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x31, 0xd0, 0x24, 0x1c, 0x61, 0xb1, 0x10, 0x98, 0xb2, 0x58, 0x9d, 0x3c, 0xb9, 0x12,
	0x3c, 0x01, 0x4c, 0xed, 0xc0, 0x92, 0x17, 0xa8, 0xdc, 0xf8, 0x88, 0x2c, 0x35, 0x77, 0xc1, 0x4e,
	0x23, 0xe5, 0xed, 0x11, 0xb5, 0xca, 0xd8, 0xf1, 0xff, 0xee, 0xd7, 0xfd, 0xfa, 0xa0, 0x6e, 0xb9,
	0xef, 0x99, 0xec, 0x10, 0x79, 0x64, 0x59, 0xf2, 0x80, 0x14, 0x78, 0x5c, 0xbe, 0x74, 0xcc, 0xdd,
	0x01, 0xd7, 0x27, 0xbc, 0x3f, 0x7e, 0xaf, 0x1d, 0xcd, 0xb9, 0xb3, 0xf2, 0x50, 0x6c, 0xd0, 0x79,
	0x8c, 0xf2, 0x15, 0xee, 0x3c, 0x4e, 0xa1, 0xc5, 0x5d, 0xf0, 0x4a, 0x68, 0x61, 0x6e, 0x9b, 0x2a,
	0x83, 0xad, 0x97, 0x4f, 0xb0, 0x18, 0x0e, 0x2e, 0x90, 0x5a, 0x68, 0x61, 0xaa, 0xcd, 0x55, 0x93,
	0xa3, 0x7c, 0x86, 0xc2, 0x61, 0xda, 0x85, 0x49, 0x15, 0x5a, 0x98, 0xfa, 0xef, 0xe0, 0x30, 0x6d,
	0xa7, 0xcf, 0x1a, 0x00, 0xa9, 0x8d, 0xf3, 0x30, 0x06, 0xa6, 0x55, 0x84, 0xf2, 0x0b, 0x53, 0x72,
	0x1d, 0x5e, 0x9e, 0x59, 0x42, 0x95, 0xf0, 0xe7, 0x88, 0xd4, 0xa2, 0xba, 0xd6, 0xc2, 0x3c, 0x34,
	0xff, 0x59, 0x5a, 0x28, 0xfb, 0xfc, 0x43, 0xdd, 0x68, 0x61, 0xee, 0xdf, 0x1e, 0x6d, 0xd6, 0xb2,
	0x67, 0x2d, 0xfb, 0x41, 0x73, 0x73, 0x2e, 0xed, 0x8b, 0x13, 0x7e, 0xff, 0x0d, 0x00, 0x00, 0xff,
	0xff, 0xce, 0x31, 0xe6, 0xe5, 0x14, 0x01, 0x00, 0x00,
}
