// Code generated by protoc-gen-go. DO NOT EDIT.
// source: openiot/system.proto

package openiot

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Always unencrypted message header
// to be able to find decryption key by device id.
type Header struct {
	// Unique (at least within network) device ID.
	DeviceId uint64 `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// CRC of message data before encryption (if desired).
	Crc uint32 `protobuf:"varint,2,opt,name=crc,proto3" json:"crc,omitempty"`
	// Indicates that message contains key exchange request / response
	KeyExchange          bool     `protobuf:"varint,3,opt,name=key_exchange,json=keyExchange,proto3" json:"key_exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{0}
}

func (m *Header) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Header.Unmarshal(m, b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Header.Marshal(b, m, deterministic)
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return xxx_messageInfo_Header.Size(m)
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

func (m *Header) GetDeviceId() uint64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

func (m *Header) GetCrc() uint32 {
	if m != nil {
		return m.Crc
	}
	return 0
}

func (m *Header) GetKeyExchange() bool {
	if m != nil {
		return m.KeyExchange
	}
	return false
}

type MessageInfo struct {
	// Auto-incremented sequence number to drop duplicates
	// uint32 should last about 136 years even if device / controller
	// will be sending messages every second
	Sequence             uint32   `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessageInfo) Reset()         { *m = MessageInfo{} }
func (m *MessageInfo) String() string { return proto.CompactTextString(m) }
func (*MessageInfo) ProtoMessage()    {}
func (*MessageInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{1}
}

func (m *MessageInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessageInfo.Unmarshal(m, b)
}
func (m *MessageInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessageInfo.Marshal(b, m, deterministic)
}
func (m *MessageInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessageInfo.Merge(m, src)
}
func (m *MessageInfo) XXX_Size() int {
	return xxx_messageInfo_MessageInfo.Size(m)
}
func (m *MessageInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MessageInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MessageInfo proto.InternalMessageInfo

func (m *MessageInfo) GetSequence() uint32 {
	if m != nil {
		return m.Sequence
	}
	return 0
}

// Diffie-Hellman key exchange: device to controller
type KeyExchangeRequest struct {
	DhP                  uint64   `protobuf:"varint,1,opt,name=dh_p,json=dhP,proto3" json:"dh_p,omitempty"`
	DhG                  uint64   `protobuf:"varint,2,opt,name=dh_g,json=dhG,proto3" json:"dh_g,omitempty"`
	DhA                  []uint32 `protobuf:"varint,3,rep,packed,name=dh_a,json=dhA,proto3" json:"dh_a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyExchangeRequest) Reset()         { *m = KeyExchangeRequest{} }
func (m *KeyExchangeRequest) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeRequest) ProtoMessage()    {}
func (*KeyExchangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{2}
}

func (m *KeyExchangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeRequest.Unmarshal(m, b)
}
func (m *KeyExchangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeRequest.Marshal(b, m, deterministic)
}
func (m *KeyExchangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeRequest.Merge(m, src)
}
func (m *KeyExchangeRequest) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeRequest.Size(m)
}
func (m *KeyExchangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeRequest proto.InternalMessageInfo

func (m *KeyExchangeRequest) GetDhP() uint64 {
	if m != nil {
		return m.DhP
	}
	return 0
}

func (m *KeyExchangeRequest) GetDhG() uint64 {
	if m != nil {
		return m.DhG
	}
	return 0
}

func (m *KeyExchangeRequest) GetDhA() []uint32 {
	if m != nil {
		return m.DhA
	}
	return nil
}

// Diffie-Hellman key exchange: controller to device
type KeyExchangeResponse struct {
	DhB                  []uint32 `protobuf:"varint,1,rep,packed,name=dh_b,json=dhB,proto3" json:"dh_b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *KeyExchangeResponse) Reset()         { *m = KeyExchangeResponse{} }
func (m *KeyExchangeResponse) String() string { return proto.CompactTextString(m) }
func (*KeyExchangeResponse) ProtoMessage()    {}
func (*KeyExchangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{3}
}

func (m *KeyExchangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_KeyExchangeResponse.Unmarshal(m, b)
}
func (m *KeyExchangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_KeyExchangeResponse.Marshal(b, m, deterministic)
}
func (m *KeyExchangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_KeyExchangeResponse.Merge(m, src)
}
func (m *KeyExchangeResponse) XXX_Size() int {
	return xxx_messageInfo_KeyExchangeResponse.Size(m)
}
func (m *KeyExchangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_KeyExchangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_KeyExchangeResponse proto.InternalMessageInfo

func (m *KeyExchangeResponse) GetDhB() []uint32 {
	if m != nil {
		return m.DhB
	}
	return nil
}

// Request to join IoT network from device.
// If device uses encryption it must initiate key exchange
// prior to joining.
type SystemJoinRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Manufacturer         string   `protobuf:"bytes,2,opt,name=manufacturer,proto3" json:"manufacturer,omitempty"`
	ProductUrl           string   `protobuf:"bytes,3,opt,name=product_url,json=productUrl,proto3" json:"product_url,omitempty"`
	ProtobufUrl          string   `protobuf:"bytes,4,opt,name=protobuf_url,json=protobufUrl,proto3" json:"protobuf_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemJoinRequest) Reset()         { *m = SystemJoinRequest{} }
func (m *SystemJoinRequest) String() string { return proto.CompactTextString(m) }
func (*SystemJoinRequest) ProtoMessage()    {}
func (*SystemJoinRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{4}
}

func (m *SystemJoinRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemJoinRequest.Unmarshal(m, b)
}
func (m *SystemJoinRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemJoinRequest.Marshal(b, m, deterministic)
}
func (m *SystemJoinRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemJoinRequest.Merge(m, src)
}
func (m *SystemJoinRequest) XXX_Size() int {
	return xxx_messageInfo_SystemJoinRequest.Size(m)
}
func (m *SystemJoinRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemJoinRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemJoinRequest proto.InternalMessageInfo

func (m *SystemJoinRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SystemJoinRequest) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *SystemJoinRequest) GetProductUrl() string {
	if m != nil {
		return m.ProductUrl
	}
	return ""
}

func (m *SystemJoinRequest) GetProtobufUrl() string {
	if m != nil {
		return m.ProtobufUrl
	}
	return ""
}

// Controller (server) response to JoinRequest
type SystemJoinResponse struct {
	// Server's name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Server's timestamp
	Timestamp            uint32   `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemJoinResponse) Reset()         { *m = SystemJoinResponse{} }
func (m *SystemJoinResponse) String() string { return proto.CompactTextString(m) }
func (*SystemJoinResponse) ProtoMessage()    {}
func (*SystemJoinResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{5}
}

func (m *SystemJoinResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemJoinResponse.Unmarshal(m, b)
}
func (m *SystemJoinResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemJoinResponse.Marshal(b, m, deterministic)
}
func (m *SystemJoinResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemJoinResponse.Merge(m, src)
}
func (m *SystemJoinResponse) XXX_Size() int {
	return xxx_messageInfo_SystemJoinResponse.Size(m)
}
func (m *SystemJoinResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemJoinResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemJoinResponse proto.InternalMessageInfo

func (m *SystemJoinResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SystemJoinResponse) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

// Deveice request to leave IoT network
type SystemLeaveRequest struct {
	Reason               string   `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemLeaveRequest) Reset()         { *m = SystemLeaveRequest{} }
func (m *SystemLeaveRequest) String() string { return proto.CompactTextString(m) }
func (*SystemLeaveRequest) ProtoMessage()    {}
func (*SystemLeaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{6}
}

func (m *SystemLeaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemLeaveRequest.Unmarshal(m, b)
}
func (m *SystemLeaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemLeaveRequest.Marshal(b, m, deterministic)
}
func (m *SystemLeaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemLeaveRequest.Merge(m, src)
}
func (m *SystemLeaveRequest) XXX_Size() int {
	return xxx_messageInfo_SystemLeaveRequest.Size(m)
}
func (m *SystemLeaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemLeaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SystemLeaveRequest proto.InternalMessageInfo

func (m *SystemLeaveRequest) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

// Controller response to leave network request
type SystemLeaveResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SystemLeaveResponse) Reset()         { *m = SystemLeaveResponse{} }
func (m *SystemLeaveResponse) String() string { return proto.CompactTextString(m) }
func (*SystemLeaveResponse) ProtoMessage()    {}
func (*SystemLeaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_477c448daeb2d28d, []int{7}
}

func (m *SystemLeaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemLeaveResponse.Unmarshal(m, b)
}
func (m *SystemLeaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemLeaveResponse.Marshal(b, m, deterministic)
}
func (m *SystemLeaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemLeaveResponse.Merge(m, src)
}
func (m *SystemLeaveResponse) XXX_Size() int {
	return xxx_messageInfo_SystemLeaveResponse.Size(m)
}
func (m *SystemLeaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemLeaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SystemLeaveResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Header)(nil), "openiot.Header")
	proto.RegisterType((*MessageInfo)(nil), "openiot.MessageInfo")
	proto.RegisterType((*KeyExchangeRequest)(nil), "openiot.KeyExchangeRequest")
	proto.RegisterType((*KeyExchangeResponse)(nil), "openiot.KeyExchangeResponse")
	proto.RegisterType((*SystemJoinRequest)(nil), "openiot.SystemJoinRequest")
	proto.RegisterType((*SystemJoinResponse)(nil), "openiot.SystemJoinResponse")
	proto.RegisterType((*SystemLeaveRequest)(nil), "openiot.SystemLeaveRequest")
	proto.RegisterType((*SystemLeaveResponse)(nil), "openiot.SystemLeaveResponse")
}

func init() { proto.RegisterFile("openiot/system.proto", fileDescriptor_477c448daeb2d28d) }

var fileDescriptor_477c448daeb2d28d = []byte{
	// 357 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x5f, 0xab, 0xd3, 0x30,
	0x18, 0xc6, 0xa9, 0x2d, 0x73, 0x7d, 0xbb, 0x81, 0xcb, 0x54, 0x8a, 0x0a, 0xd6, 0x5c, 0x55, 0x10,
	0xbd, 0xf0, 0x13, 0x28, 0xf8, 0x67, 0xea, 0x40, 0x22, 0xbb, 0xf1, 0xa6, 0x64, 0xcd, 0xbb, 0xb5,
	0x6c, 0x4d, 0x7a, 0x92, 0x74, 0x9c, 0x7d, 0x8a, 0xf3, 0x95, 0x0f, 0xcd, 0xd2, 0xed, 0x0c, 0xce,
	0x5d, 0xf2, 0xe3, 0xc9, 0x9b, 0x1f, 0xcf, 0x0b, 0xcf, 0x55, 0x8b, 0xb2, 0x56, 0xf6, 0x93, 0x39,
	0x1a, 0x8b, 0xcd, 0xc7, 0x56, 0x2b, 0xab, 0xc8, 0x53, 0x4f, 0xe9, 0x7f, 0x18, 0xfd, 0x44, 0x2e,
	0x50, 0x93, 0xd7, 0x10, 0x0b, 0x3c, 0xd4, 0x25, 0x16, 0xb5, 0x48, 0x83, 0x2c, 0xc8, 0x23, 0x36,
	0x3e, 0x81, 0x85, 0x20, 0xcf, 0x20, 0x2c, 0x75, 0x99, 0x3e, 0xc9, 0x82, 0x7c, 0xca, 0xfa, 0x23,
	0x79, 0x07, 0x93, 0x1d, 0x1e, 0x0b, 0xbc, 0x2d, 0x2b, 0x2e, 0xb7, 0x98, 0x86, 0x59, 0x90, 0x8f,
	0x59, 0xb2, 0xc3, 0xe3, 0x37, 0x8f, 0xe8, 0x7b, 0x48, 0x96, 0x68, 0x0c, 0xdf, 0xe2, 0x42, 0x6e,
	0x14, 0x79, 0x05, 0x63, 0x83, 0x37, 0x1d, 0xca, 0x12, 0xdd, 0xfc, 0x29, 0x3b, 0xdf, 0xe9, 0x12,
	0xc8, 0xef, 0xcb, 0x4b, 0xd6, 0x63, 0x63, 0xc9, 0x0c, 0x22, 0x51, 0x15, 0xad, 0xb7, 0x09, 0x45,
	0xf5, 0xd7, 0xa3, 0xad, 0x33, 0x71, 0xe8, 0x87, 0x47, 0x3c, 0x0d, 0xb3, 0xb0, 0x97, 0x13, 0xd5,
	0x17, 0x9a, 0xc3, 0xfc, 0x6a, 0x9c, 0x69, 0x95, 0x34, 0xe8, 0x93, 0xeb, 0x34, 0x18, 0x92, 0x5f,
	0xe9, 0x5d, 0x00, 0xb3, 0x7f, 0xae, 0x99, 0x5f, 0xaa, 0x96, 0xc3, 0xc7, 0x04, 0x22, 0xc9, 0x9b,
	0x93, 0x66, 0xcc, 0xdc, 0x99, 0x50, 0x98, 0x34, 0x5c, 0x76, 0x1b, 0x5e, 0xda, 0x4e, 0xa3, 0x76,
	0x06, 0x31, 0xbb, 0x62, 0xe4, 0x2d, 0x24, 0xad, 0x56, 0xa2, 0x2b, 0x6d, 0xd1, 0xe9, 0xbd, 0xeb,
	0x24, 0x66, 0xe0, 0xd1, 0x4a, 0xef, 0xfb, 0xd6, 0xdc, 0x02, 0xd6, 0xdd, 0xc6, 0x25, 0x22, 0x97,
	0x48, 0x06, 0xb6, 0xd2, 0x7b, 0xfa, 0x1d, 0xc8, 0x43, 0x21, 0xaf, 0xfe, 0x98, 0xd1, 0x1b, 0x88,
	0x6d, 0xdd, 0xa0, 0xb1, 0xbc, 0x69, 0xfd, 0x6a, 0x2e, 0x80, 0x7e, 0x18, 0xe6, 0xfc, 0x41, 0x7e,
	0x38, 0x57, 0xfa, 0x12, 0x46, 0x1a, 0xb9, 0x51, 0xd2, 0x4f, 0xf2, 0x37, 0xfa, 0x02, 0xe6, 0x57,
	0xe9, 0xd3, 0xb7, 0xeb, 0x91, 0x33, 0xfb, 0x7c, 0x1f, 0x00, 0x00, 0xff, 0xff, 0xb1, 0xa7, 0x03,
	0xb5, 0x46, 0x02, 0x00, 0x00,
}
