/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "common.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(Message, Message, AUTO)



