/* Automatically generated nanopb header */
/* Generated by 0.4.1-dev */

#ifndef PB_OPENIOT_SYSTEM_PB_H_INCLUDED
#define PB_OPENIOT_SYSTEM_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _DeviceInfoRequest {
    char dummy_field;
} DeviceInfoRequest;

typedef struct _DeviceInfoResponse {
    pb_callback_t name;
    pb_callback_t manufacturer;
    pb_callback_t product_url;
    pb_callback_t protobuf_url;
} DeviceInfoResponse;

typedef struct _LeaveRequest {
    pb_callback_t reason;
} LeaveRequest;

typedef struct _LeaveResponse {
    char dummy_field;
} LeaveResponse;

typedef struct _HeaderMessage {
    uint64_t device_id;
    bool system_message;
    pb_size_t which_encryption;
    union {
        bool plain;
        pb_byte_t aes_iv[16];
    } encryption;
} HeaderMessage;

typedef struct _JoinRequest {
    uint64_t dh_p;
    uint64_t dh_g;
    pb_size_t dh_a_count;
    uint32_t dh_a[16];
} JoinRequest;

typedef struct _JoinResponse {
    pb_size_t dh_b_count;
    uint32_t dh_b[16];
} JoinResponse;

typedef struct _SystemMessage {
    pb_size_t which_message;
    union {
        JoinRequest join_request;
        JoinResponse join_response;
        LeaveRequest leave_request;
        LeaveResponse leave_response;
        DeviceInfoRequest device_info_request;
        DeviceInfoResponse device_info_response;
    } message;
} SystemMessage;


/* Initializer values for message structs */
#define HeaderMessage_init_default               {0, 0, 0, {0}}
#define SystemMessage_init_default               {0, {JoinRequest_init_default}}
#define JoinRequest_init_default                 {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define JoinResponse_init_default                {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define LeaveRequest_init_default                {{{NULL}, NULL}}
#define LeaveResponse_init_default               {0}
#define DeviceInfoRequest_init_default           {0}
#define DeviceInfoResponse_init_default          {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define HeaderMessage_init_zero                  {0, 0, 0, {0}}
#define SystemMessage_init_zero                  {0, {JoinRequest_init_zero}}
#define JoinRequest_init_zero                    {0, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define JoinResponse_init_zero                   {0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define LeaveRequest_init_zero                   {{{NULL}, NULL}}
#define LeaveResponse_init_zero                  {0}
#define DeviceInfoRequest_init_zero              {0}
#define DeviceInfoResponse_init_zero             {{{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceInfoResponse_name_tag              1
#define DeviceInfoResponse_manufacturer_tag      2
#define DeviceInfoResponse_product_url_tag       3
#define DeviceInfoResponse_protobuf_url_tag      4
#define LeaveRequest_reason_tag                  1
#define HeaderMessage_plain_tag                  5
#define HeaderMessage_aes_iv_tag                 6
#define HeaderMessage_device_id_tag              1
#define HeaderMessage_system_message_tag         2
#define JoinRequest_dh_p_tag                     1
#define JoinRequest_dh_g_tag                     2
#define JoinRequest_dh_a_tag                     3
#define JoinResponse_dh_b_tag                    1
#define SystemMessage_join_request_tag           1
#define SystemMessage_join_response_tag          2
#define SystemMessage_leave_request_tag          3
#define SystemMessage_leave_response_tag         4
#define SystemMessage_device_info_request_tag    5
#define SystemMessage_device_info_response_tag   6

/* Struct field encoding specification for nanopb */
#define HeaderMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   device_id,         1) \
X(a, STATIC,   SINGULAR, BOOL,     system_message,    2) \
X(a, STATIC,   ONEOF,    BOOL,     (encryption,plain,encryption.plain),   5) \
X(a, STATIC,   ONEOF,    FIXED_LENGTH_BYTES, (encryption,aes_iv,encryption.aes_iv),   6)
#define HeaderMessage_CALLBACK NULL
#define HeaderMessage_DEFAULT NULL

#define SystemMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,join_request,message.join_request),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,join_response,message.join_response),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,leave_request,message.leave_request),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,leave_response,message.leave_response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,device_info_request,message.device_info_request),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,device_info_response,message.device_info_response),   6)
#define SystemMessage_CALLBACK NULL
#define SystemMessage_DEFAULT NULL
#define SystemMessage_message_join_request_MSGTYPE JoinRequest
#define SystemMessage_message_join_response_MSGTYPE JoinResponse
#define SystemMessage_message_leave_request_MSGTYPE LeaveRequest
#define SystemMessage_message_leave_response_MSGTYPE LeaveResponse
#define SystemMessage_message_device_info_request_MSGTYPE DeviceInfoRequest
#define SystemMessage_message_device_info_response_MSGTYPE DeviceInfoResponse

#define JoinRequest_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   dh_p,              1) \
X(a, STATIC,   SINGULAR, UINT64,   dh_g,              2) \
X(a, STATIC,   REPEATED, UINT32,   dh_a,              3)
#define JoinRequest_CALLBACK NULL
#define JoinRequest_DEFAULT NULL

#define JoinResponse_FIELDLIST(X, a) \
X(a, STATIC,   REPEATED, UINT32,   dh_b,              1)
#define JoinResponse_CALLBACK NULL
#define JoinResponse_DEFAULT NULL

#define LeaveRequest_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   reason,            1)
#define LeaveRequest_CALLBACK pb_default_field_callback
#define LeaveRequest_DEFAULT NULL

#define LeaveResponse_FIELDLIST(X, a) \

#define LeaveResponse_CALLBACK NULL
#define LeaveResponse_DEFAULT NULL

#define DeviceInfoRequest_FIELDLIST(X, a) \

#define DeviceInfoRequest_CALLBACK NULL
#define DeviceInfoRequest_DEFAULT NULL

#define DeviceInfoResponse_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, STRING,   name,              1) \
X(a, CALLBACK, SINGULAR, STRING,   manufacturer,      2) \
X(a, CALLBACK, SINGULAR, STRING,   product_url,       3) \
X(a, CALLBACK, SINGULAR, STRING,   protobuf_url,      4)
#define DeviceInfoResponse_CALLBACK pb_default_field_callback
#define DeviceInfoResponse_DEFAULT NULL

extern const pb_msgdesc_t HeaderMessage_msg;
extern const pb_msgdesc_t SystemMessage_msg;
extern const pb_msgdesc_t JoinRequest_msg;
extern const pb_msgdesc_t JoinResponse_msg;
extern const pb_msgdesc_t LeaveRequest_msg;
extern const pb_msgdesc_t LeaveResponse_msg;
extern const pb_msgdesc_t DeviceInfoRequest_msg;
extern const pb_msgdesc_t DeviceInfoResponse_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define HeaderMessage_fields &HeaderMessage_msg
#define SystemMessage_fields &SystemMessage_msg
#define JoinRequest_fields &JoinRequest_msg
#define JoinResponse_fields &JoinResponse_msg
#define LeaveRequest_fields &LeaveRequest_msg
#define LeaveResponse_fields &LeaveResponse_msg
#define DeviceInfoRequest_fields &DeviceInfoRequest_msg
#define DeviceInfoResponse_fields &DeviceInfoResponse_msg

/* Maximum encoded size of messages (where known) */
#define HeaderMessage_size                       31
/* SystemMessage_size depends on runtime parameters */
#define JoinRequest_size                         118
#define JoinResponse_size                        96
/* LeaveRequest_size depends on runtime parameters */
#define LeaveResponse_size                       0
#define DeviceInfoRequest_size                   0
/* DeviceInfoResponse_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
