/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Header, Header, AUTO)


PB_BIND(Message, Message, AUTO)


PB_BIND(SystemJoinRequest, SystemJoinRequest, AUTO)


PB_BIND(SystemJoinResponse, SystemJoinResponse, AUTO)


PB_BIND(SystemLeaveRequest, SystemLeaveRequest, AUTO)


PB_BIND(SystemLeaveResponse, SystemLeaveResponse, AUTO)


PB_BIND(SystemDeviceInfoRequest, SystemDeviceInfoRequest, AUTO)


PB_BIND(SystemDeviceInfoResponse, SystemDeviceInfoResponse, AUTO)



