/* Automatically generated nanopb constant definitions */
/* Generated by 0.4.1-dev */

#include "system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(HeaderMessage, HeaderMessage, AUTO)


PB_BIND(SystemMessage, SystemMessage, AUTO)


PB_BIND(JoinRequest, JoinRequest, AUTO)


PB_BIND(JoinResponse, JoinResponse, AUTO)


PB_BIND(LeaveRequest, LeaveRequest, AUTO)


PB_BIND(LeaveResponse, LeaveResponse, AUTO)


PB_BIND(DeviceInfoRequest, DeviceInfoRequest, AUTO)


PB_BIND(DeviceInfoResponse, DeviceInfoResponse, AUTO)



