/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "openiot/sensor/multisensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(MultiSensorStatus, MultiSensorStatus, AUTO)


PB_BIND(Temperature, Temperature, AUTO)


PB_BIND(Humidity, Humidity, AUTO)


PB_BIND(Battery, Battery, AUTO)


PB_BIND(AmbientLight, AmbientLight, AUTO)



