/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.2-dev */

#include "openiot/sensor/multisensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(sensor_MultiSensorStatus, sensor_MultiSensorStatus, AUTO)


PB_BIND(sensor_Temperature, sensor_Temperature, AUTO)


PB_BIND(sensor_Humidity, sensor_Humidity, AUTO)


PB_BIND(sensor_Battery, sensor_Battery, AUTO)



